In [1]:
import numpy as np

In [8]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [10]:
a2 = np.full([3,3],7)
a2

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [12]:
a2 = np.eye(7)
a2

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])