In [40]:
import numpy as np

In [41]:


# data = np.genfromtxt(
#     file,
#     delimiter=",",
#     dtype=None,
#     encoding="utf-8",
#     names=True
# )



In [42]:
def read_file(filepath):
    student_list = []
    with open(filepath,"r") as f: 
        next(f)
        for line in f:
            row = line.strip().split(",")
            student_list.append(row)
    f.close()
    return student_list


In [43]:
data = read_file(r"D:\data-science-journey\Data_Science\Data\Student_data.csv")

In [44]:
data[0]

['1', 'Aarav Sharma', 'Ahmedabad', '78', '82', '75', '88', '80.75']

1.

In [45]:
len(data)

205

2.

In [46]:
len(data[0][3:7])
data[0][3:7]


['78', '82', '75', '88']

3.

In [47]:
data = np.array(data)

set(data[:, 2])

{np.str_('Ahmedabad'),
 np.str_('Amritsar'),
 np.str_('Bangalore'),
 np.str_('Bhopal'),
 np.str_('Chandigarh'),
 np.str_('Chennai'),
 np.str_('Delhi'),
 np.str_('Hyderabad'),
 np.str_('Indore'),
 np.str_('Jaipur'),
 np.str_('Kanpur'),
 np.str_('Kochi'),
 np.str_('Kolkata'),
 np.str_('Lucknow'),
 np.str_('Mumbai'),
 np.str_('Nagpur'),
 np.str_('Patna'),
 np.str_('Pune'),
 np.str_('Rajkot'),
 np.str_('Surat'),
 np.str_('Vadodara')}

4.  5. 6. 7. 

In [48]:
totals = []

for d in range(len(data)):
    subjects = data[d, 3:7].astype(float)

    sum_of_subjects = np.sum(subjects)
    avg_of_subjects = np.average(subjects)
    totals.append(sum_of_subjects)
    higest_per = np.max(data[:,7].astype(float))
    lowest_per = np.min(data[:,7].astype(float))

data = np.column_stack((data, totals))
print(higest_per)
print(lowest_per)
# data


98.5
66.75


9.

In [49]:

filtered_data = data[:, 7].astype(float) > 90

print(f"Number of students with total > 80: {np.sum(filtered_data)}")

Number of students with total > 80: 65


10.

In [50]:
filtered_data1 = data[:, 7].astype(float) < 70

print(f"Number of students with total > 80: {np.sum(filtered_data1)}")

Number of students with total > 80: 20


11.

In [51]:
max_maths_marks = np.max(data[:, 3].astype(float) )
max_sci_marks = np.max(data[:, 4].astype(float) )
max_maths_marks
max_sci_marks

np.float64(99.0)

# Subject-wise Analysis Questions

16. & 17.

In [52]:
all_sub_avg = []

for d in range(len(data)):
    subjects = data[d, 3].astype(float)
    subjects1 = data[d, 4].astype(float)
    subjects2 = data[d, 5].astype(float)
    subjects3= data[d, 6].astype(float)

    avg_of_subjects = np.average(subjects)
    avg_of_subjects1 = np.average(subjects1)
    avg_of_subjects2 = np.average(subjects2)
    avg_of_subjects3 = np.average(subjects3)

all_sub_avg.append((avg_of_subjects, "maths"))
all_sub_avg.append((avg_of_subjects1, "sci"))
all_sub_avg.append((avg_of_subjects2, "Eng"))
all_sub_avg.append((avg_of_subjects3, "comp"))

all_sub_avg
max_from_all_sub = max(all_sub_avg)
min_from_all_sub = min(all_sub_avg)
max_from_all_sub
min_from_all_sub

(np.float64(79.0), 'Eng')

In [53]:
top_10_in_maths=np.sort(data[:,3].astype(float))[::-1]
print("Find top 10 students in Mathematics")
for  i in range(10):
    print(top_10_in_maths[i],end=', ')

Find top 10 students in Mathematics
98.0, 98.0, 98.0, 97.0, 97.0, 97.0, 97.0, 97.0, 97.0, 96.0, 

26.

In [54]:

max_from_all_sub = max(all_sub_avg)
print("hardest based on average marks" , max_from_all_sub)


hardest based on average marks (np.float64(83.0), 'comp')


27.

In [55]:
min_from_all_sub = min(all_sub_avg)
print("easiest based on average marks" , min_from_all_sub)

easiest based on average marks (np.float64(79.0), 'Eng')


28.

In [56]:
result = np.var(data[:, 3].astype(float))
print("variance of Mathematics marks", round(result, 2))



variance of Mathematics marks 89.01


29.

In [57]:
result = np.std(data[:,4].astype(float))
print(round(result, 1))

9.3


30.

In [58]:
average = np.mean(data[:,5].astype(float))
print(average)

82.54146341463415


# 🏙 City-wise Student Analysis Questions

In [59]:
cities = data[:, 2]

unique_cities = np.unique(cities)

max_count = 0
max_city = ""

for city in unique_cities:
    count = np.sum(cities == city)

    if count > max_count:
        max_count = count
        max_city = city

print("City:", max_city)
print("Number of students:", max_count)

City: Ahmedabad
Number of students: 29


32. 33. 35. 36 .


In [60]:
max_avg = np.max(data[:,7].astype(float))
min_avg = np.min(data[:,7].astype(float))
for d in data:
    if float(d[7]) == max_avg:
        print("city has the highest average percentage is ",d[2],"Which is ",max_avg)
    if float(d[7]) == min_avg:
        print("city has the lowest average percentage is ",d[2],"Which is ",min_avg)
        

city has the highest average percentage is  Jaipur Which is  98.5
city has the lowest average percentage is  Surat Which is  66.75
city has the highest average percentage is  Kolkata Which is  98.5
city has the highest average percentage is  Delhi Which is  98.5
city has the lowest average percentage is  Patna Which is  66.75


34.

In [61]:
cities = data[:, 2]

unique_cities = np.unique(cities)

max_count = 0
max_city = ""

for city in unique_cities:
    count = np.sum(cities == city)


    max_count = count
    max_city = city

    print("City:", max_city)
    print("Number of students:", max_count)

City: Ahmedabad
Number of students: 29
City: Amritsar
Number of students: 2
City: Bangalore
Number of students: 8
City: Bhopal
Number of students: 1
City: Chandigarh
Number of students: 1
City: Chennai
Number of students: 3
City: Delhi
Number of students: 23
City: Hyderabad
Number of students: 2
City: Indore
Number of students: 14
City: Jaipur
Number of students: 14
City: Kanpur
Number of students: 10
City: Kochi
Number of students: 5
City: Kolkata
Number of students: 16
City: Lucknow
Number of students: 4
City: Mumbai
Number of students: 13
City: Nagpur
Number of students: 1
City: Patna
Number of students: 13
City: Pune
Number of students: 4
City: Rajkot
Number of students: 13
City: Surat
Number of students: 17
City: Vadodara
Number of students: 12


37.

In [62]:
cities = data[:, 2]

unique_cities = np.unique(cities)

max_count = 0
max_city = ""

for city in unique_cities:
    count = np.sum(cities == city)

    if city == "Ahmedabad" :
        max_count = count
        max_city = city
        print("City:", max_city)
        print("Number of students:", max_count)
        ahmedabad_avg = data[data[:, 2] == "Ahmedabad", 7].astype(float)
        print("Avg of all students in Ahmedabad is :", ahmedabad_avg)

    if city == "Surat":
        max_count = count
        max_city = city

        print("City:", max_city)
        print("Number of students:", max_count)
        surat_avg = data[data[:, 2] == "Surat", 7].astype(float)
        print("Avg of all students in Ahmedabad is :", surat_avg)
        

City: Ahmedabad
Number of students: 29
Avg of all students in Ahmedabad is : [80.75 82.   71.5  81.   71.5  76.25 83.   72.   92.75 77.25 69.75 78.
 79.75 80.   84.75 81.75 83.   77.   80.   84.   73.   78.75 93.75 79.
 80.   78.   75.75 80.   81.  ]
City: Surat
Number of students: 17
Avg of all students in Ahmedabad is : [92.5  71.25 70.25 81.75 88.   80.75 86.5  88.5  87.   69.5  73.75 68.
 66.75 82.75 86.5  68.   85.5 ]


#  Student Ranking Questions

41 42 43 44

In [63]:

total_col = data[:, 7].astype(float)
sorted_indices = np.argsort(total_col)[::-1]
ranked_students = data[sorted_indices]

print("Rank\tStudent\t\tTotal Marks")
for rank, student in enumerate(ranked_students, start=1):
    print(f"{rank}\t{student[1]}\t\t{student[7]}")

for rank, student in enumerate(ranked_students[:5], start=1):
    print(f"{rank}\t{student[1]}\t\t{student[7]}")



Rank	Student		Total Marks
1	Ayushi Singh		98.50
2	Riddhi Das		98.50
3	Muskaan Sharma		98.50
4	Tanisha Sharma		98.00
5	Priyanka Mehta		97.50
6	Ananya Das		97.50
7	Pallavi Jain		97.50
8	Anvi Sharma		97.50
9	Pooja Roy		97.50
10	Shraddha Kapoor		97.00
11	Reena Das		97.00
12	Nikita Sharma		96.75
13	Saloni Kapoor		96.75
14	Reema Kapoor		96.50
15	Muskan Arora		96.50
16	Ishani Rao		96.00
17	Taniya Kapoor		96.00
18	Anika Roy		95.75
19	Sanjana Mehra		95.75
20	Meera Kapoor		95.75
21	Shivani Gupta		95.75
22	Komal Singh		95.50
23	Rupal Shah		95.50
24	Radhika Rao		95.50
25	Ira Singh		95.50
26	Anvi Roy		95.50
27	Simran Kaur		95.00
28	Aditi Rao		94.75
29	Vaishali Roy		94.75
30	Neeti Sharma		94.75
31	Neelam Nair		94.50
32	Priya Nair		94.25
33	Manya Kapoor		94.25
34	Khushboo Das		94.00
35	Trupti Rao		94.00
36	Sonal Kapoor		94.00
37	Diya Kapoor		94.00
38	Mitali Sharma		94.00
39	Ritika Patel		93.75
40	Shreya Menon		93.50
41	Mitali Rao		93.50
42	Mehak Jain		93.50
43	Monika Singh		93.50
44	Rupal Singh		93.0

In [64]:

print("Rank\tStudent\t\tTotal Marks")
for rank, student in enumerate(ranked_students, start=1):
    if (np.array(student[7]).astype(float)) >= 80 and (np.array(student[7]).astype(float)) <=90:
        print(f"{rank}\t{student[1]}\t\t{student[7]}")

Rank	Student		Total Marks
66	Prerna Kapoor		90.00
67	Preeti Nair		89.75
68	Meenal Sharma		89.75
69	Payal Singh		89.50
70	Neha Yadav		89.50
71	Tanisha Mehta		89.50
72	Twinkle Jain		89.50
73	Ritika Roy		89.50
74	Sakshi Rao		89.50
75	Kavya Iyer		89.50
76	Sakshi Mehta		89.50
77	Kiara Jain		88.50
78	Krupa Patel		88.50
79	Heena Mehta		88.50
80	Heer Mehta		88.50
81	Anita Verma		88.50
82	Nidhi Joshi		88.00
83	Palak Mehta		88.00
84	Aashi Mehta		87.75
85	Divyanshi Jain		87.50
86	Payal Sharma		87.50
87	Khushi Mehra		87.50
88	Deepika Roy		87.50
89	Roshni Jain		87.50
90	Ishan Verma		87.50
91	Jyoti Patel		87.00
92	Pooja Gupta		86.75
93	Ananya Singh		86.75
94	Shruti Das		86.50
95	Krisha Das		86.50
96	Khushi Patel		86.50
97	Namrata Shah		86.50
98	Sneha Reddy		86.25
99	Komal Patel		86.00
100	Nisha Patel		85.50
101	Ankita Roy		85.50
102	Tanvi Shah		85.50
103	Aarohi Patel		84.75
104	Jay Patel		84.00
105	Anurag Jain		84.00
106	Mohit Verma		83.75
107	Karan Verma		83.00
108	Dhruv Patel		83.00
109	Vatsal Sha

In [65]:
unique_cities
print("Rank\tStudent\t\tTotal Marks")
for rank, student in enumerate(ranked_students, start=1):
    
    print(f"{rank}\t{np.unique(student[2])}\t\t{student[7]}")

Rank	Student		Total Marks
1	['Delhi']		98.50
2	['Kolkata']		98.50
3	['Jaipur']		98.50
4	['Delhi']		98.00
5	['Mumbai']		97.50
6	['Kolkata']		97.50
7	['Indore']		97.50
8	['Jaipur']		97.50
9	['Kolkata']		97.50
10	['Jaipur']		97.00
11	['Kolkata']		97.00
12	['Delhi']		96.75
13	['Jaipur']		96.75
14	['Delhi']		96.50
15	['Chandigarh']		96.50
16	['Bangalore']		96.00
17	['Jaipur']		96.00
18	['Kolkata']		95.75
19	['Jaipur']		95.75
20	['Jaipur']		95.75
21	['Lucknow']		95.75
22	['Delhi']		95.50
23	['Vadodara']		95.50
24	['Bangalore']		95.50
25	['Delhi']		95.50
26	['Kolkata']		95.50
27	['Amritsar']		95.00
28	['Hyderabad']		94.75
29	['Kolkata']		94.75
30	['Delhi']		94.75
31	['Kochi']		94.50
32	['Pune']		94.25
33	['Mumbai']		94.25
34	['Kolkata']		94.00
35	['Bangalore']		94.00
36	['Mumbai']		94.00
37	['Jaipur']		94.00
38	['Jaipur']		94.00
39	['Ahmedabad']		93.75
40	['Kochi']		93.50
41	['Bangalore']		93.50
42	['Indore']		93.50
43	['Delhi']		93.50
44	['Delhi']		93.00
45	['Jaipur']		93.00
46	['Ahmedabad']

49.


In [66]:
 
sorted_data = data[np.argsort(data[:, 2])]
cities = np.unique(sorted_data[:, 2])
print("Topper of each city:\n")
for city in cities:
    city_data = sorted_data[sorted_data[:, 2] == city]
    topper = city_data[np.argmax(city_data[:, 7].astype(float))]
    print(city, "->", topper)

Topper of each city:

Ahmedabad -> ['156' 'Ritika Patel' 'Ahmedabad' '93' '94' '92' '96' '93.75' '375.0']
Amritsar -> ['22' 'Simran Kaur' 'Amritsar' '94' '96' '93' '97' '95.00' '380.0']
Bangalore -> ['126' 'Ishani Rao' 'Bangalore' '95' '97' '94' '98' '96.00' '384.0']
Bhopal -> ['21' 'Aman Verma' 'Bhopal' '82' '84' '80' '85' '82.75' '331.0']
Chandigarh -> ['30' 'Muskan Arora' 'Chandigarh' '96' '95' '97' '98' '96.50' '386.0']
Chennai -> ['80' 'Aesha Iyer' 'Chennai' '88' '90' '91' '92' '90.25' '361.0']
Delhi -> ['192' 'Ayushi Singh' 'Delhi' '98' '97' '99' '100' '98.50' '394.0']
Hyderabad -> ['46' 'Aditi Rao' 'Hyderabad' '94' '95' '93' '97' '94.75' '379.0']
Indore -> ['66' 'Pallavi Jain' 'Indore' '97' '96' '98' '99' '97.50' '390.0']
Jaipur -> ['136' 'Muskaan Sharma' 'Jaipur' '98' '97' '99' '100' '98.50' '394.0']
Kanpur -> ['20' 'Neha Yadav' 'Kanpur' '89' '91' '88' '90' '89.50' '358.0']
Kochi -> ['90' 'Neelam Nair' 'Kochi' '93' '95' '94' '96' '94.50' '378.0']
Kolkata -> ['168' 'Riddhi Das' 

# 📈 Statistical Analysis Questions


51.

In [67]:
round(np.mean(data[:, 3].astype(int)),2)

np.float64(82.67)

In [68]:
round(np.var(data[:, 7].astype(float)),2)

np.float64(87.66)

In [69]:
round(np.std(data[:, 6].astype(float)),2) 

np.float64(9.25)

In [70]:
math = data[:, 3].astype(float)
science = data[:, 4].astype(float)

correlation = np.corrcoef(math, science)[0, 1]

print("Correlation between Math and Science:", correlation)

Correlation between Math and Science: 0.9931531928824037


66

In [71]:
result = data[data[:, 3].astype(float) > 90]

print(result)

[['2' 'Diya Patel' 'Surat' '91' '89' '94' '96' '92.50' '370.0']
 ['6' 'Priya Nair' 'Pune' '93' '95' '92' '97' '94.25' '377.0']
 ['10' 'Meera Kapoor' 'Jaipur' '95' '94' '96' '98' '95.75' '383.0']
 ['14' 'Ishita Sharma' 'Delhi' '92' '90' '91' '94' '91.75' '367.0']
 ['22' 'Simran Kaur' 'Amritsar' '94' '96' '93' '97' '95.00' '380.0']
 ['26' 'Anjali Mehra' 'Delhi' '91' '92' '90' '94' '91.75' '367.0']
 ['30' 'Muskan Arora' 'Chandigarh' '96' '95' '97' '98' '96.50' '386.0']
 ['34' 'Shreya Menon' 'Kochi' '92' '94' '93' '95' '93.50' '374.0']
 ['38' 'Rupal Shah' 'Vadodara' '95' '97' '94' '96' '95.50' '382.0']
 ['42' 'Mitali Sharma' 'Jaipur' '93' '92' '95' '96' '94.00' '376.0']
 ['46' 'Aditi Rao' 'Hyderabad' '94' '95' '93' '97' '94.75' '379.0']
 ['50' 'Reema Kapoor' 'Delhi' '96' '97' '95' '98' '96.50' '386.0']
 ['54' 'Anushka Das' 'Kolkata' '91' '93' '92' '94' '92.50' '370.0']
 ['58' 'Ira Singh' 'Delhi' '95' '96' '94' '97' '95.50' '382.0']
 ['62' 'Nehal Patel' 'Ahmedabad' '92' '91' '93' '95' '92.7

In [72]:
result = data[data[:, 4].astype(float) < 70]

print(result)

[['15' 'Rajat Kumar' 'Patna' '65' '68' '66' '70' '67.25' '269.0']
 ['19' 'Harsh Trivedi' 'Ahmedabad' '71' '69' '74' '72' '71.50' '286.0']
 ['31' 'Ritesh Singh' 'Patna' '66' '67' '69' '71' '68.25' '273.0']
 ['39' 'Sachin Kumar' 'Delhi' '67' '69' '65' '70' '67.75' '271.0']
 ['51' 'Vivek Sharma' 'Patna' '65' '66' '68' '70' '67.25' '269.0']
 ['67' 'Harshit Singh' 'Delhi' '66' '68' '67' '70' '67.75' '271.0']
 ['75' 'Devansh Mehta' 'Ahmedabad' '68' '69' '70' '72' '69.75' '279.0']
 ['87' 'Hemant Verma' 'Patna' '67' '68' '66' '70' '67.75' '271.0']
 ['111' 'Harsh Mehta' 'Rajkot' '66' '68' '67' '70' '67.75' '271.0']
 ['127' 'Ronit Patel' 'Surat' '67' '69' '66' '70' '68.00' '272.0']
 ['137' 'Sahil Mehta' 'Surat' '65' '67' '66' '69' '66.75' '267.0']
 ['145' 'Shyam Verma' 'Kanpur' '68' '69' '67' '71' '68.75' '275.0']
 ['161' 'Deepak Kumar' 'Kanpur' '66' '68' '67' '70' '67.75' '271.0']
 ['177' 'Akhil Patel' 'Surat' '67' '69' '66' '70' '68.00' '272.0']
 ['193' 'Vikram Kumar' 'Patna' '66' '67' '65' '6

In [73]:
result = data[data[:, 2] == "Ahmedabad"]

print(result)

[['1' 'Aarav Sharma' 'Ahmedabad' '78' '82' '75' '88' '80.75' '323.0']
 ['9' 'Arjun Desai' 'Ahmedabad' '81' '79' '83' '85' '82.00' '328.0']
 ['19' 'Harsh Trivedi' 'Ahmedabad' '71' '69' '74' '72' '71.50' '286.0']
 ['29' 'Chirag Modi' 'Ahmedabad' '80' '78' '82' '84' '81.00' '324.0']
 ['35' 'Jay Shah' 'Ahmedabad' '70' '72' '71' '73' '71.50' '286.0']
 ['41' 'Akash Patel' 'Ahmedabad' '75' '77' '74' '79' '76.25' '305.0']
 ['49' 'Dhruv Patel' 'Ahmedabad' '82' '84' '81' '85' '83.00' '332.0']
 ['55' 'Hardik Modi' 'Ahmedabad' '71' '73' '70' '74' '72.00' '288.0']
 ['62' 'Nehal Patel' 'Ahmedabad' '92' '91' '93' '95' '92.75' '371.0']
 ['69' 'Mayank Desai' 'Ahmedabad' '76' '78' '75' '80' '77.25' '309.0']
 ['75' 'Devansh Mehta' 'Ahmedabad' '68' '69' '70' '72' '69.75' '279.0']
 ['81' 'Tushar Patel' 'Ahmedabad' '77' '79' '76' '80' '78.00' '312.0']
 ['89' 'Deep Shah' 'Ahmedabad' '78' '80' '79' '82' '79.75' '319.0']
 ['97' 'Om Patel' 'Ahmedabad' '79' '81' '78' '82' '80.00' '320.0']
 ['101' 'Aarohi Patel' 

In [74]:
result = data[data[:, 7].astype(float) > 85]

print(result)

[['2' 'Diya Patel' 'Surat' '91' '89' '94' '96' '92.50' '370.0']
 ['4' 'Ananya Singh' 'Rajkot' '85' '88' '84' '90' '86.75' '347.0']
 ['6' 'Priya Nair' 'Pune' '93' '95' '92' '97' '94.25' '377.0']
 ['8' 'Kavya Iyer' 'Chennai' '88' '91' '90' '89' '89.50' '358.0']
 ['10' 'Meera Kapoor' 'Jaipur' '95' '94' '96' '98' '95.75' '383.0']
 ['12' 'Sneha Reddy' 'Hyderabad' '84' '87' '86' '88' '86.25' '345.0']
 ['14' 'Ishita Sharma' 'Delhi' '92' '90' '91' '94' '91.75' '367.0']
 ['16' 'Pooja Gupta' 'Lucknow' '86' '89' '85' '87' '86.75' '347.0']
 ['18' 'Riya Das' 'Kolkata' '90' '93' '92' '95' '92.50' '370.0']
 ['20' 'Neha Yadav' 'Kanpur' '89' '91' '88' '90' '89.50' '358.0']
 ['22' 'Simran Kaur' 'Amritsar' '94' '96' '93' '97' '95.00' '380.0']
 ['24' 'Nidhi Joshi' 'Nagpur' '87' '86' '89' '90' '88.00' '352.0']
 ['26' 'Anjali Mehra' 'Delhi' '91' '92' '90' '94' '91.75' '367.0']
 ['28' 'Sakshi Rao' 'Bangalore' '88' '90' '91' '89' '89.50' '358.0']
 ['30' 'Muskan Arora' 'Chandigarh' '96' '95' '97' '98' '96.50' 

In [75]:
index = np.argsort(data[:, 7].astype(float))[::-1]

result = data[index]

print(result)

[['192' 'Ayushi Singh' 'Delhi' ... '100' '98.50' '394.0']
 ['168' 'Riddhi Das' 'Kolkata' ... '100' '98.50' '394.0']
 ['136' 'Muskaan Sharma' 'Jaipur' ... '100' '98.50' '394.0']
 ...
 ['15' 'Rajat Kumar' 'Patna' ... '70' '67.25' '269.0']
 ['137' 'Sahil Mehta' 'Surat' ... '69' '66.75' '267.0']
 ['193' 'Vikram Kumar' 'Patna' ... '69' '66.75' '267.0']]


In [76]:
index = np.argsort(data[:, 3].astype(float))

result = data[index]

print(result)

[['15' 'Rajat Kumar' 'Patna' ... '70' '67.25' '269.0']
 ['51' 'Vivek Sharma' 'Patna' ... '70' '67.25' '269.0']
 ['137' 'Sahil Mehta' 'Surat' ... '69' '66.75' '267.0']
 ...
 ['136' 'Muskaan Sharma' 'Jaipur' ... '100' '98.50' '394.0']
 ['168' 'Riddhi Das' 'Kolkata' ... '100' '98.50' '394.0']
 ['192' 'Ayushi Singh' 'Delhi' ... '100' '98.50' '394.0']]


In [77]:
index = np.argsort(data[:, 7].astype(float))[::-1]

top_20 = data[index][:20]

print(top_20)

[['192' 'Ayushi Singh' 'Delhi' '98' '97' '99' '100' '98.50' '394.0']
 ['168' 'Riddhi Das' 'Kolkata' '98' '99' '97' '100' '98.50' '394.0']
 ['136' 'Muskaan Sharma' 'Jaipur' '98' '97' '99' '100' '98.50' '394.0']
 ['200' 'Tanisha Sharma' 'Delhi' '97' '99' '96' '100' '98.00' '392.0']
 ['184' 'Priyanka Mehta' 'Mumbai' '97' '98' '96' '99' '97.50' '390.0']
 ['152' 'Ananya Das' 'Kolkata' '97' '96' '98' '99' '97.50' '390.0']
 ['66' 'Pallavi Jain' 'Indore' '97' '96' '98' '99' '97.50' '390.0']
 ['94' 'Anvi Sharma' 'Jaipur' '97' '98' '96' '99' '97.50' '390.0']
 ['118' 'Pooja Roy' 'Kolkata' '97' '98' '96' '99' '97.50' '390.0']
 ['176' 'Shraddha Kapoor' 'Jaipur' '96' '98' '95' '99' '97.00' '388.0']
 ['144' 'Reena Das' 'Kolkata' '96' '98' '95' '99' '97.00' '388.0']
 ['110' 'Nikita Sharma' 'Delhi' '96' '95' '97' '99' '96.75' '387.0']
 ['86' 'Saloni Kapoor' 'Jaipur' '96' '97' '95' '99' '96.75' '387.0']
 ['50' 'Reema Kapoor' 'Delhi' '96' '97' '95' '98' '96.50' '386.0']
 ['30' 'Muskan Arora' 'Chandigarh'

In [78]:
result = data[
    data[:, 3].astype(float) == data[:, 4].astype(float)
]

print(result)

[]


In [79]:
index = np.argsort(data[:, 7].astype(float))[::-1]

top_20 = data[index][:20]

print(top_20)

[['192' 'Ayushi Singh' 'Delhi' '98' '97' '99' '100' '98.50' '394.0']
 ['168' 'Riddhi Das' 'Kolkata' '98' '99' '97' '100' '98.50' '394.0']
 ['136' 'Muskaan Sharma' 'Jaipur' '98' '97' '99' '100' '98.50' '394.0']
 ['200' 'Tanisha Sharma' 'Delhi' '97' '99' '96' '100' '98.00' '392.0']
 ['184' 'Priyanka Mehta' 'Mumbai' '97' '98' '96' '99' '97.50' '390.0']
 ['152' 'Ananya Das' 'Kolkata' '97' '96' '98' '99' '97.50' '390.0']
 ['66' 'Pallavi Jain' 'Indore' '97' '96' '98' '99' '97.50' '390.0']
 ['94' 'Anvi Sharma' 'Jaipur' '97' '98' '96' '99' '97.50' '390.0']
 ['118' 'Pooja Roy' 'Kolkata' '97' '98' '96' '99' '97.50' '390.0']
 ['176' 'Shraddha Kapoor' 'Jaipur' '96' '98' '95' '99' '97.00' '388.0']
 ['144' 'Reena Das' 'Kolkata' '96' '98' '95' '99' '97.00' '388.0']
 ['110' 'Nikita Sharma' 'Delhi' '96' '95' '97' '99' '96.75' '387.0']
 ['86' 'Saloni Kapoor' 'Jaipur' '96' '97' '95' '99' '96.75' '387.0']
 ['50' 'Reema Kapoor' 'Delhi' '96' '97' '95' '98' '96.50' '386.0']
 ['30' 'Muskan Arora' 'Chandigarh'

In [80]:
marks = data[:, 3:7].astype(float)

result = data[np.any(marks < 40, axis=1)]

print(result)

[]


In [81]:
# 77
support = data[data[:, 7].astype(float) < 70]

print(support)

[['15' 'Rajat Kumar' 'Patna' '65' '68' '66' '70' '67.25' '269.0']
 ['31' 'Ritesh Singh' 'Patna' '66' '67' '69' '71' '68.25' '273.0']
 ['39' 'Sachin Kumar' 'Delhi' '67' '69' '65' '70' '67.75' '271.0']
 ['47' 'Saurabh Jain' 'Indore' '68' '70' '69' '72' '69.75' '279.0']
 ['51' 'Vivek Sharma' 'Patna' '65' '66' '68' '70' '67.25' '269.0']
 ['67' 'Harshit Singh' 'Delhi' '66' '68' '67' '70' '67.75' '271.0']
 ['75' 'Devansh Mehta' 'Ahmedabad' '68' '69' '70' '72' '69.75' '279.0']
 ['87' 'Hemant Verma' 'Patna' '67' '68' '66' '70' '67.75' '271.0']
 ['95' 'Sumit Kumar' 'Kanpur' '69' '70' '68' '71' '69.50' '278.0']
 ['104' 'Parthiv Shah' 'Surat' '68' '70' '69' '71' '69.50' '278.0']
 ['111' 'Harsh Mehta' 'Rajkot' '66' '68' '67' '70' '67.75' '271.0']
 ['127' 'Ronit Patel' 'Surat' '67' '69' '66' '70' '68.00' '272.0']
 ['137' 'Sahil Mehta' 'Surat' '65' '67' '66' '69' '66.75' '267.0']
 ['145' 'Shyam Verma' 'Kanpur' '68' '69' '67' '71' '68.75' '275.0']
 ['161' 'Deepak Kumar' 'Kanpur' '66' '68' '67' '70' '

In [82]:
cities = np.unique(data[:, 2])

best_city = ""
highest_avg = 0

for city in cities:
    city_data = data[data[:, 2] == city]

    avg = np.mean(city_data[:, 7].astype(float))

    if avg > highest_avg:
        highest_avg = avg
        best_city = city

print(best_city, highest_avg)

Chandigarh 96.5


In [83]:
subjects = data[:, 3:7].astype(float)

std = np.std(subjects, axis=0)

subject_names = ["Math", "Science", "English", "Computer"]

print(subject_names[np.argmax(std)])

English


In [84]:
math_avg = np.mean(data[:, 3].astype(float))
computer_avg = np.mean(data[:, 6].astype(float))

print("Math Average:", math_avg)
print("Computer Average:", computer_avg)

if computer_avg > math_avg:
    print("Yes")
else:
    print("No")

Math Average: 82.67317073170732
Computer Average: 85.73170731707317
Yes


In [85]:
subjects = data[:, 3:7].astype(float)

std = np.std(subjects, axis=0)

subject_names = ["Math", "Science", "English", "Computer"]

print(subject_names[np.argmin(std)])

Computer


In [86]:
subjects = data[:, 3:7].astype(float)

std = np.std(subjects, axis=0)

subject_names = ["Math", "Science", "English", "Computer"]

print(subject_names[np.argmin(std)])

Computer


#  NumPy Practice Questions

86

In [87]:
marks = np.array(data[:, 3:7], dtype=float)

print(marks)

[[ 78.  82.  75.  88.]
 [ 91.  89.  94.  96.]
 [ 67.  71.  73.  69.]
 [ 85.  88.  84.  90.]
 [ 76.  74.  79.  81.]
 [ 93.  95.  92.  97.]
 [ 72.  70.  68.  75.]
 [ 88.  91.  90.  89.]
 [ 81.  79.  83.  85.]
 [ 95.  94.  96.  98.]
 [ 69.  72.  70.  74.]
 [ 84.  87.  86.  88.]
 [ 77.  75.  78.  80.]
 [ 92.  90.  91.  94.]
 [ 65.  68.  66.  70.]
 [ 86.  89.  85.  87.]
 [ 74.  76.  73.  79.]
 [ 90.  93.  92.  95.]
 [ 71.  69.  74.  72.]
 [ 89.  91.  88.  90.]
 [ 82.  84.  80.  85.]
 [ 94.  96.  93.  97.]
 [ 68.  70.  72.  71.]
 [ 87.  86.  89.  90.]
 [ 79.  81.  77.  83.]
 [ 91.  92.  90.  94.]
 [ 73.  75.  71.  76.]
 [ 88.  90.  91.  89.]
 [ 80.  78.  82.  84.]
 [ 96.  95.  97.  98.]
 [ 66.  67.  69.  71.]
 [ 85.  87.  84.  88.]
 [ 78.  79.  76.  80.]
 [ 92.  94.  93.  95.]
 [ 70.  72.  71.  73.]
 [ 89.  88.  90.  91.]
 [ 81.  83.  79.  84.]
 [ 95.  97.  94.  96.]
 [ 67.  69.  65.  70.]
 [ 86.  88.  87.  89.]
 [ 75.  77.  74.  79.]
 [ 93.  92.  95.  96.]
 [ 72.  74.  73.  75.]
 [ 88.  90.

In [88]:
print("Shape:", data.shape)

Shape: (205, 9)


In [89]:

print("Dimensions:", data.ndim)

Dimensions: 2


In [90]:
math = data[:, 3]

print(math)

['78' '91' '67' '85' '76' '93' '72' '88' '81' '95' '69' '84' '77' '92'
 '65' '86' '74' '90' '71' '89' '82' '94' '68' '87' '79' '91' '73' '88'
 '80' '96' '66' '85' '78' '92' '70' '89' '81' '95' '67' '86' '75' '93'
 '72' '88' '79' '94' '68' '87' '82' '96' '65' '84' '77' '91' '71' '88'
 '80' '95' '69' '86' '78' '92' '73' '89' '81' '97' '66' '85' '76' '93'
 '72' '90' '79' '94' '68' '87' '83' '95' '70' '88' '77' '92' '74' '89'
 '81' '96' '67' '86' '78' '93' '71' '90' '82' '97' '69' '87' '79' '94'
 '75' '91' '84' '72' '95' '68' '86' '93' '77' '89' '81' '96' '66' '85'
 '78' '92' '73' '90' '82' '97' '69' '87' '76' '94' '71' '88' '80' '95'
 '67' '86' '79' '93' '74' '91' '70' '89' '83' '98' '65' '84' '77' '92'
 '72' '90' '81' '96' '68' '87' '78' '94' '75' '91' '82' '97' '69' '86'
 '77' '93' '71' '89' '80' '95' '66' '85' '78' '92' '73' '90' '81' '98'
 '68' '87' '79' '94' '74' '91' '82' '96' '67' '86' '77' '93' '72' '89'
 '80' '97' '69' '85' '78' '92' '75' '90' '83' '98' '66' '84' '79' '95'
 '71' 

In [91]:
math = data[:, 3].astype(float)

In [92]:
marks = data[:, 3:7].astype(float)

row_total = np.sum(marks, axis=1)

print(row_total)

[323. 370. 280. 347. 310. 377. 285. 358. 328. 383. 285. 345. 310. 367.
 269. 347. 302. 370. 286. 358. 331. 380. 281. 352. 320. 367. 295. 358.
 324. 386. 273. 344. 313. 374. 286. 358. 327. 382. 271. 350. 305. 376.
 294. 358. 319. 379. 279. 352. 332. 386. 269. 342. 312. 370. 288. 359.
 323. 382. 280. 350. 316. 371. 295. 358. 327. 390. 271. 346. 309. 376.
 290. 366. 320. 382. 279. 354. 335. 383. 284. 361. 312. 374. 299. 362.
 328. 387. 271. 348. 319. 378. 287. 366. 331. 390. 278. 354. 320. 379.
 303. 370. 339. 292. 383. 278. 350. 377. 312. 362. 327. 387. 271. 346.
 316. 374. 295. 363. 332. 390. 280. 354. 308. 382. 288. 358. 324. 384.
 272. 350. 320. 376. 299. 367. 284. 360. 336. 394. 267. 342. 311. 372.
 292. 364. 328. 388. 275. 351. 315. 379. 304. 370. 331. 390. 280. 350.
 312. 375. 288. 362. 324. 384. 271. 346. 316. 374. 296. 363. 327. 394.
 276. 354. 320. 382. 300. 367. 332. 388. 272. 350. 312. 376. 291. 359.
 323. 390. 279. 346. 316. 372. 303. 364. 336. 394. 267. 342. 320. 383.
 288. 

In [93]:
marks = data[:, 3:7].astype(float)

column_average = np.mean(marks, axis=0)

print(column_average)

[82.67317073 84.11707317 82.54146341 85.73170732]
